#!/bin/bash

system_type=$(uname -s)

mkdir -p "$HOME/.local/bin"

if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping Vim"
    vim +'PlugInstall --sync' +qa
fi

if command -v pipx >/dev/null 2>&1; then
  echo "Installing pipx"
  python3 -m pip install --user pipx
fi

if [[ "$system_type" =~ "Darwin" ]]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
      echo "Installing homebrew"
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
      echo "Updating homebrew bundle"
      brew bundle --global
      brew link --force gettext
  fi

  if [ -d "$HOME/.config/iterm2" ]; then
      echo "Setting iTerm preference folder"
      defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

  if command -v mpm >/dev/null 2>&1; then
    echo "Installing mpm"
    pipx install meta-package-manager
    ln -s "$(command -v mpm)" /usr/local/sbin/mpm
  fi

  if command -v kubens >/dev/null 2>&1; then
    mkdir -p ~/workspace
    pushd ~/workspace || return 1
    git clone git@github.com:aca/go-kubectx.git
    pushd go-kubectx || return 1
    go install ./cmd/kubens
    go install ./cmd/kubectx
    popd || return 1
    popd || return 1
  fi

elif [[ "$system_type" == "Linux" ]]; then
  if ! command -v diff-so-fancy 2>&1; then
    curl -L "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy" > ~/.local/bin/diff-so-fancy
    chmod +x ~/.local/bin/diff-so-fancy
  fi
fi
