#!/bin/bash

system_type=$(uname -s)

if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping Vim"
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if command -v pipsi >/dev/null 2>&1; then
  echo "Installing pipsi"
  curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
fi

if [[ "$system_type" == "Darwin" ]]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
      echo "Installing homebrew"
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
      echo "Updating homebrew bundle"
      brew bundle --global
      brew link --force gettext
  fi

  if [ -d "$HOME/.config/iterm2" ]; then
      echo "Setting iTerm preference folder"
      defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

  if command -v mpm >/dev/null 2>&1; then
    echo "Installing mpm"
    pipsi --bin-dir /usr/local/sbin/ install meta-package-manager
  fi
fi
